### ISSUE TITLE
Data Set Hierarchy Modelling

### ISSUE THREAD

**Issue by elatoskinas** [lightingft/appinventor-sources#9]
Based on the Chart hierarchy (#8), the necessary Data Set hierarchy should be designed following the Chart hierarchy issue.

It is important to note that certain Charts may support the same Data Set (this especially applies for point-based Charts)

Additional consideration should be taken for future support for other data sets, for example data sets that have 4 points for one entry (Candle Stick chart)

Design should support the following:
- [x] Coordinate Data Set (Line, Scatterplot, Area charts)
- [x] Bar Data Set (Bar chart)
- [x] Pie Data Set (Pie chart)

Future support for the following data sets should be considered:
- [x] Candle Data Set (5 value entry, consisting of x value, shadow upper and lower values, open and closing values)
- [x] Bubble Data Set (x and y values as well as radius)

**Comment by elatoskinas** [comment]
Two designs presented, one which focuses on grouping the data sets, and one which has one class of Data Sets per Chart Type.

**Comment by lightingft** [comment]
For now, the hierarchy will suffice. As all the Chart implementations are done sequentially, additional abstractions can be added.

**Comment by elatoskinas** [comment]
Data Set Concept might be redefined later. Up for future consideration.

**Comment by elatoskinas** [comment]
![image](https://user-images.githubusercontent.com/34982762/59128972-cb7d4000-896b-11e9-8ec1-5aac1a3bf0d9.png)


For now, the following hierarchy is chosen. When the implementation moves on to support new Data types, changes might occur.
